### ISSUE TITLE
Only collapse on file open

### ISSUE THREAD

**Issue by migig** [natehitze/SeeUsingsLater#1]
This plugin keeps collapsing while the file is open and being used.

For example, if I press `alt-up` or `alt-down` to reorder the usings lines, the plugin will collapse the section.

It needs to listen for the document open event, perform its work, then do nothing further. Not only is this a bug, it indicates that it is not efficient as it may be listening for the wrong events?

**Comment by natehitze** [comment]
This is actually by design - I very, very rarely _manually_ change usings lines. 

If you use the automated tools available (such as the reorder using function or "add usings" code fix), they will expand the usings lines region. The extension collapses those after the modification takes places.

If you want to take a moment to look at the code, it is pretty simple. If you can come up with a better solution to this problem, I would welcome a pull request.

**Comment by migig** [comment]
Oh no not by design... I do tend to manually fiddle with the usings. :sob:

I looked at the code but I've never written a plugin before, so I don't understand it. :dizzy_face:

Thanks though.

**Comment by grokky1** [comment]
This extension collapses using every time I do something with them. If I add/remove one of them, it kicks in.

I agree with @migig that it should listen for document open.

**Comment by natehitze** [comment]
@grokky1 The idea is that you don't manually mess with using statements anymore. Let VisualStudio/ReSharper handle adding or removing the statements. Since publishing this, I've _never_ messed with usings.

If that isn't convincing - what about a compromise? Maybe adding a short delay before the usings region is collapsed?

**Comment by grokky1** [comment]
@laughinggoose I'm not sure what most people do, but I deal with usings regularly. Different dev styles I guess...

A delay would be really useful!!

Question is, how long? A second would go by in a flash, one would need a little while to do all the editing. So what then? 10 seconds? But that may be too long for some people, because they expect the extension to kick in quickly. Ideally it should be configurable, but even though I've never written a VS extension before, I'm assuming that would be alot of effort.

**Comment by natehitze** [comment]
@migig @grokky1 I figured out a compromise that I think will work. The extension will no longer collapse the usings region if your caret is in the region or the line immediately following. This should allow you to manually change the usings.

I just published an update to the marketplace - version 1.3 is what you'll want to install: https://marketplace.visualstudio.com/items?itemName=Nhitze.SeeUsingsLater

**Comment by grokky1** [comment]
Nice idea. But how is this new feature supposed to work exactly? Problem is when you open a file, the caret is in the usings block... So it never collapses for me.

**Comment by natehitze** [comment]
Ah yes, thank you. I just updated the code and published v1.4 of the extension. It will actually automatically collapse the usings region when a document is first opened no matter where the caret is.

**Comment by grokky1** [comment]
I'm gonna check it out now... are we back to the original behavior then, before the changes in this thread?

**Comment by natehitze** [comment]
A mix of the 2 - the usings will be automatically collapsed when the document opens, no matter where the caret is. After that, the usages region will only auto-collapse if the caret is not in it.

**Comment by grokky1** [comment]
Good compromise
